name: slots
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_it: ^7.6.7
  kbspinningwheel: ^1.0.3
  roulette: ^0.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/items/
    - assets/games/slot/
    - assets/games/pokies/
    - assets/games/roulette/
    - assets/icons/
    - assets/landing/
    - assets/shared/
    - assets/gift/
  fonts:
    - family: aso
      fonts:
        - asset: assets/fonts/aso/AlfaSlabOne-Regular.ttf
    - family: akro
      fonts:
        - asset: assets/fonts/akro/Akrobat-Regular.otf
